name: build deb

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Create Assets
        run: apt install dh-make && make deb
          #- name: Build Docker Image
          #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      - name: Upload TEST Asset
        id: upload-release-asset-test
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: TODO
          asset_name: TODO
          asset_content_type: text/plain
      - name: Upload Deb Asset
        id: upload-release-asset-deb
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ../palma_${{ github.ref }}_all.deb
          asset_name: palma_${{ github.ref }}_all.deb
          #asset_content_type: text/plain
