name: build deb

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - name: Set release version env
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Create Assets
        run: sudo apt install dh-make && make deb
          #- name: Build Docker Image
          #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      - name: Upload Deb Asset
        id: upload-release-asset-deb
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ../palma_${{ steps.vars.outputs.tag }}_all.deb
          asset_name: palma_${{ steps.vars.outputs.tag }}_all.deb
          asset_content_type: application/zip
